### ISSUE TITLE
Clean out old rooted slots from slot table

### ISSUE THREAD

**Issue by linuskendall** [rpcpool/solana-accountsdb-connector#14]
Change this query:

https://github.com/rpcpool/solana-accountsdb-connector/blob/f6fe797544c4e422944f8ae95b7f1b23c32756dd/lib/src/postgres_target.rs#L249

to:

`DELETE FROM slot WHERE slot < $1 `

This will stop the slot table from filling up with rooted slots.

**Comment by linuskendall** [comment]
Also in this same transaction we can add the following (if it's not too slow):

```
DELETE FROM account_write WHERE pubkey IN (SELECT DISTINCT pubkey FROM account_write WHERE slot = $1) AND slot < $1
```

This can also be created as a trigger on the UPDATE SLOT

**Comment by linuskendall** [comment]
^ This will stop the account_write table from growing.

**Comment by charleschege** [comment]
@linuskendall 0d2ed76 solves this issue. Can you confirm that
```
DELETE FROM account_write WHERE pubkey IN (SELECT DISTINCT pubkey FROM account_write WHERE slot = $1) AND slot < $1
```
is correctly added
